"""
Per-window signal transforms.

All functions operate on (C, W) tensors — C sensor channels, W time samples.
Applied independently to each modality; no cross-modal operations.

RMS normalisation is always applied. Augmentations and interventions are applied
only during training, controlled by the dataset's is_train flag.

Intervention types (synthetic causal interventions, interv_idx 1-7):
    1 = white noise      — flat spectrum (rain / sensor static)
    2 = brown noise      — 1/f² (wind / low-freq rumble)
    3 = pink noise       — 1/f  (generic ambient noise)
    4 = green noise      — band-pass centred ~500 Hz (mid-freq ambient)
    5 = low-freq osc     — thunder / distant heavy traffic
    6 = high-freq chirp  — mechanical squeaks
    7 = bird chirps      — modulated burst vocalisations

All noise generators return a (L,) mono tensor before channel-expansion.
apply_intervention handles scaling and channel broadcasting.
"""

import math
import torch
import torch.nn.functional as F


# ---------------------------------------------------------------------------
# Core normalisation (always applied)
# ---------------------------------------------------------------------------

def rms_normalize(x: torch.Tensor, eps: float = 1e-8) -> torch.Tensor:
    """
    Per-window RMS normalisation.  x: (C, W) → (C, W).
    Per-channel so multi-axis sensors (e.g., accel) are normalised independently.

    Do NOT use global dataset statistics — vehicle passage events are
    non-stationary; global normalisation suppresses the transient signal.
    """
    rms = x.pow(2).mean(dim=-1, keepdim=True).sqrt()   # (C, 1)
    return x / (rms + eps)


# ---------------------------------------------------------------------------
# Optional training augmentations
# ---------------------------------------------------------------------------

def add_awgn(x: torch.Tensor, snr_db_range: tuple = (10, 30)) -> torch.Tensor:
    """
    Additive white Gaussian noise at a uniformly-sampled SNR in [snr_db_range].
    x: (C, W). Keeps the model robust to ambient noise floor variation.
    """
    snr_db = torch.empty(1).uniform_(snr_db_range[0], snr_db_range[1]).item()
    snr_linear = 10 ** (snr_db / 10.0)
    signal_power = x.pow(2).mean()
    noise_power = signal_power / (snr_linear + 1e-8)
    return x + torch.randn_like(x) * noise_power.sqrt()


def random_time_shift(x: torch.Tensor, max_shift_frac: float = 0.1) -> torch.Tensor:
    """
    Circular shift along the time axis by a random fraction of the window width.
    x: (C, W). Encourages temporal invariance in the encoder.
    """
    W = x.shape[-1]
    max_shift = max(1, int(W * max_shift_frac))
    shift = torch.randint(-max_shift, max_shift + 1, (1,)).item()
    return torch.roll(x, shifts=shift, dims=-1)


# ---------------------------------------------------------------------------
# Noise generators  (each returns a (L,) mono tensor, un-scaled)
# ---------------------------------------------------------------------------

def _white_noise(L: int) -> torch.Tensor:
    """Flat-spectrum (rain / sensor static)."""
    return torch.randn(L)


def _brown_noise(L: int) -> torch.Tensor:
    """
    Brownian / red noise — 1/f² power spectrum (wind / low-freq rumble).
    Generated by cumulative sum of white noise then high-pass de-drifted.
    """
    noise = torch.cumsum(torch.randn(L), dim=0)
    return noise - noise.mean()


def _pink_noise(L: int) -> torch.Tensor:
    """
    Pink noise — 1/f power spectrum (generic ambient background).
    Voss-McCartney algorithm: sum octave-decimated white noise streams.
    """
    n_octaves = max(1, int(math.log2(L)))
    pink = torch.zeros(L)
    for k in range(n_octaves):
        step = 2 ** k
        white = torch.randn(math.ceil(L / step))
        # Repeat each value for `step` samples (staircase upsample)
        upsampled = white.repeat_interleave(step)[:L]
        pink = pink + upsampled
    pink = pink - pink.mean()
    return pink


def _green_noise(L: int, sample_rate: int) -> torch.Tensor:
    """
    Green noise — band-pass centred near the most perceptually significant
    frequencies (~500 Hz for audio; ~15 Hz for seismic).  Implemented as
    pink noise filtered by a Gaussian spectral envelope.

    The centre frequency adapts to sample_rate:
        centre = min(500, sample_rate // 8)  Hz
        width  = centre                      Hz
    """
    pink = _pink_noise(L)
    centre_hz = min(500.0, sample_rate / 8.0)
    width_hz  = centre_hz

    # Build Gaussian spectral mask in the frequency domain
    freqs = torch.fft.rfftfreq(L, d=1.0 / sample_rate)           # Hz axis
    mask  = torch.exp(-0.5 * ((freqs - centre_hz) / width_hz).pow(2))
    spectrum = torch.fft.rfft(pink)
    filtered = torch.fft.irfft(spectrum * mask, n=L)
    return filtered


def _low_freq_osc(L: int, sample_rate: int) -> torch.Tensor:
    """
    Superposition of low-frequency sinusoids with amplitude modulation.
    Mimics thunder rumble or distant heavy traffic (2–12 Hz).
    """
    t = torch.linspace(0, L / sample_rate, L, dtype=torch.float32)
    noise = (
        torch.sin(2 * math.pi * 3 * t)
        + torch.sin(2 * math.pi * 8 * t + 1.5)
    )
    # Random amplitude envelope so it doesn't look perfectly periodic
    noise = noise * (torch.randn(L) * 0.2 + 1.0)
    return noise


def _high_freq_chirp(L: int, sample_rate: int) -> torch.Tensor:
    """
    Linear frequency chirp spanning the upper quarter of the spectrum,
    shaped with a Gaussian burst envelope (mechanical squeaks).
    """
    t = torch.linspace(0, L / sample_rate, L, dtype=torch.float32)
    f_lo = sample_rate / 8.0
    f_hi = sample_rate / 3.0
    freq = torch.linspace(f_lo, f_hi, L)
    chirp = torch.sin(2 * math.pi * freq * t)
    envelope = torch.exp(-((t - t[-1] / 2) ** 2) / (0.02 + 1e-8))
    return chirp * envelope


def _bird_chirps(L: int, sample_rate: int) -> torch.Tensor:
    """
    Simulate bird vocalisations: several short, frequency-modulated bursts
    at random positions, each spanning a narrow band in the upper spectrum.

    Each burst is a rapid FM sweep (typical bird: 2–8 kHz for audio; for
    seismic this models the high-frequency tail of bird footfall vibrations).
    """
    t = torch.linspace(0, L / sample_rate, L, dtype=torch.float32)
    signal = torch.zeros(L)

    n_bursts = torch.randint(2, 6, (1,)).item()
    for _ in range(n_bursts):
        # Random centre time and duration
        t_centre = torch.rand(1).item() * (L / sample_rate)
        duration = 0.02 + torch.rand(1).item() * 0.08   # 20–100 ms
        sigma = duration / 4

        # Gaussian envelope centred at t_centre
        env = torch.exp(-0.5 * ((t - t_centre) / sigma) ** 2)

        # FM sweep: start and end frequencies in the upper quarter of the spectrum
        f_lo = sample_rate * 0.25 + torch.rand(1).item() * sample_rate * 0.25
        f_hi = f_lo + sample_rate * 0.1
        f_inst = torch.linspace(f_lo, f_hi, L)
        phase = 2 * math.pi * torch.cumsum(f_inst / sample_rate, dim=0)
        burst = torch.sin(phase) * env

        signal = signal + burst

    return signal


# ---------------------------------------------------------------------------
# Intervention dispatcher
# ---------------------------------------------------------------------------

def apply_intervention(
    x: torch.Tensor, intervention_id: int, sample_rate: int
) -> torch.Tensor:
    """
    Inject synthetic noise matching a known intervention type into signal x.

    x: (C, W)
    intervention_id:
        0 = no-op (return x unchanged)
        1 = white noise      (rain / sensor static)
        2 = brown noise      (wind / low-freq rumble)
        3 = pink noise       (generic ambient 1/f)
        4 = green noise      (mid-freq ambient, ~500 Hz band)
        5 = low-freq osc     (thunder / distant heavy traffic)
        6 = high-freq chirp  (mechanical squeaks)
        7 = bird chirps      (modulated burst vocalisations)

    Noise is scaled to ~20% of signal RMS so the vehicle signal is
    preserved while creating a detectable distributional shift.
    """
    if intervention_id == 0:
        return x

    C, L = x.shape

    if intervention_id == 1:
        noise = _white_noise(L)
    elif intervention_id == 2:
        noise = _brown_noise(L)
    elif intervention_id == 3:
        noise = _pink_noise(L)
    elif intervention_id == 4:
        noise = _green_noise(L, sample_rate)
    elif intervention_id == 5:
        noise = _low_freq_osc(L, sample_rate)
    elif intervention_id == 6:
        noise = _high_freq_chirp(L, sample_rate)
    elif intervention_id == 7:
        noise = _bird_chirps(L, sample_rate)
    else:
        return x   # unknown id — pass through

    noise = noise.unsqueeze(0).expand(C, -1).to(x.device)  # [C, L]

    signal_rms = x.pow(2).mean().sqrt()
    noise_rms  = noise.pow(2).mean().sqrt()
    target_rms = torch.clamp(signal_rms * 0.20, min=1e-4)

    return x + noise * (target_rms / (noise_rms + 1e-8))


# Number of distinct intervention types (excluding 0=no-op)
N_INTERVENTIONS = 7


def apply_all_interventions(x: torch.Tensor, sample_rate: int) -> torch.Tensor:
    """
    Return N_INTERVENTIONS+1 versions of x: [x_clean, x_interv1, ..., x_interv7].
    Each version is RMS-normalised independently.

    x: (C, W)
    Returns: (N_INTERVENTIONS+1, C, W)

    Single-sample version kept for backwards compatibility.
    Prefer apply_interventions_batch_gpu for training loops.
    """
    return torch.stack([
        rms_normalize(apply_intervention(x, k, sample_rate))
        for k in range(N_INTERVENTIONS + 1)
    ])


# ---------------------------------------------------------------------------
# Vectorised batch intervention — GPU-native, no CPU↔GPU transfers
# ---------------------------------------------------------------------------

def _noise_batch_gpu(
    interv_id: int, B: int, C: int, W: int, sample_rate: int, device: torch.device
) -> torch.Tensor:
    """
    Generate a (B, C, W) noise tensor for intervention type interv_id directly
    on `device`.  All random ops and deterministic ops stay on GPU.
    """
    if interv_id == 1:  # white
        return torch.randn(B, C, W, device=device)

    if interv_id == 2:  # brown
        noise = torch.cumsum(torch.randn(B, C, W, device=device), dim=-1)
        return noise - noise.mean(dim=-1, keepdim=True)

    if interv_id == 3:  # pink — Voss-McCartney, batched
        n_oct = max(1, int(math.log2(W)))
        pink = torch.zeros(B, C, W, device=device)
        for k in range(n_oct):
            step = 2 ** k
            n_samp = math.ceil(W / step)
            white = torch.randn(B, C, n_samp, device=device)
            upsampled = white.repeat_interleave(step, dim=-1)[:, :, :W]
            pink = pink + upsampled
        return pink - pink.mean(dim=-1, keepdim=True)

    if interv_id == 4:  # green — FFT band-pass on batched pink
        n_oct = max(1, int(math.log2(W)))
        pink = torch.zeros(B, C, W, device=device)
        for k in range(n_oct):
            step = 2 ** k
            n_samp = math.ceil(W / step)
            white = torch.randn(B, C, n_samp, device=device)
            pink = pink + white.repeat_interleave(step, dim=-1)[:, :, :W]
        pink = pink - pink.mean(dim=-1, keepdim=True)
        centre_hz = min(500.0, sample_rate / 8.0)
        freqs = torch.fft.rfftfreq(W, d=1.0 / sample_rate, device=device)
        mask = torch.exp(-0.5 * ((freqs - centre_hz) / centre_hz).pow(2))
        return torch.fft.irfft(torch.fft.rfft(pink, dim=-1) * mask, n=W, dim=-1)

    if interv_id == 5:  # low-freq oscillation — deterministic base, random amplitude
        t = torch.linspace(0, W / sample_rate, W, device=device)
        base = torch.sin(2 * math.pi * 3 * t) + torch.sin(2 * math.pi * 8 * t + 1.5)
        amp = torch.randn(B, C, W, device=device) * 0.2 + 1.0
        return base.view(1, 1, W) * amp

    if interv_id == 6:  # high-freq chirp — fully deterministic, broadcast across batch
        t = torch.linspace(0, W / sample_rate, W, device=device)
        freq = torch.linspace(sample_rate / 8.0, sample_rate / 3.0, W, device=device)
        chirp = torch.sin(2 * math.pi * freq * t)
        envelope = torch.exp(-((t - t[-1] / 2) ** 2) / (0.02 + 1e-8))
        return (chirp * envelope).view(1, 1, W).expand(B, C, W).contiguous()

    if interv_id == 7:  # bird chirps — 4 batched FM bursts
        t = torch.linspace(0, W / sample_rate, W, device=device)  # (W,)
        signal = torch.zeros(B, C, W, device=device)
        for _ in range(4):
            t_c = torch.rand(B, 1, 1, device=device) * (W / sample_rate)
            sigma = (0.02 + torch.rand(B, 1, 1, device=device) * 0.08).clamp(min=1e-4)
            env = torch.exp(-0.5 * ((t - t_c) / sigma).pow(2))        # (B, 1, W)
            f_lo = sample_rate * 0.25 + torch.rand(B, 1, 1, device=device) * sample_rate * 0.25
            f_hi = f_lo + sample_rate * 0.1
            # Instantaneous frequency: linear sweep per sample, shape (B, 1, W)
            sweep = torch.linspace(0, 1, W, device=device).view(1, 1, W)
            f_inst = f_lo + sweep * (f_hi - f_lo)
            phase = 2 * math.pi * torch.cumsum(f_inst / sample_rate, dim=-1)
            signal = signal + (torch.sin(phase) * env).expand(B, C, W)
        return signal

    return torch.zeros(B, C, W, device=device)  # unknown — pass-through noise-free


def apply_interventions_batch_gpu(
    x_batch: torch.Tensor, sample_rate: int
) -> torch.Tensor:
    """
    Vectorised multi-intervention expansion.  All noise is generated on
    x_batch.device — no CPU↔GPU transfers and no Python loop over batch samples.

    x_batch : (B, C, W) — already on GPU
    Returns  : (N_INTERVENTIONS+1, B, C, W)
                  [0] = clean (RMS-normalised)
                  [k] = x_batch + intervention-k noise (RMS-normalised), k=1..7
    """
    B, C, W = x_batch.shape
    device = x_batch.device
    sig_rms = x_batch.pow(2).mean(dim=-1, keepdim=True).sqrt()  # (B, C, 1)

    views = [_rms_normalize_batch(x_batch)]  # clean view

    for k in range(1, N_INTERVENTIONS + 1):
        noise = _noise_batch_gpu(k, B, C, W, sample_rate, device)   # (B, C, W)
        noise_rms = noise.pow(2).mean(dim=-1, keepdim=True).sqrt()
        target_rms = (sig_rms * 0.20).clamp(min=1e-4)
        mixed = x_batch + noise * (target_rms / (noise_rms + 1e-8))
        views.append(_rms_normalize_batch(mixed))

    return torch.stack(views)   # (N+1, B, C, W)


def _rms_normalize_batch(x: torch.Tensor) -> torch.Tensor:
    """x: (B, C, W) → (B, C, W), per-sample RMS normalisation."""
    rms = x.pow(2).mean(dim=-1, keepdim=True).sqrt()
    return x / (rms + 1e-8)
