# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\x1a\x1fgoogle/protobuf/timestamp.proto\"%\n\x06Tensor\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"\x9c\x02\n\nSensorData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x10\n\x08\x63hannels\x18\x02 \x03(\t\x12.\n\ntime_stamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\racoustic_data\x18\x04 \x01(\x0b\x32\x11.inference.TensorH\x00\x88\x01\x01\x12,\n\x0cseismic_data\x18\x05 \x01(\x0b\x32\x11.inference.TensorH\x01\x88\x01\x01\x12*\n\naccel_data\x18\x06 \x01(\x0b\x32\x11.inference.TensorH\x02\x88\x01\x01\x42\x10\n\x0e_acoustic_dataB\x0f\n\r_seismic_dataB\r\n\x0b_accel_data\"k\n\x0f\x44\x65tectionResult\x12*\n\x0bsensor_data\x18\x01 \x01(\x0b\x32\x15.inference.SensorData\x12\x18\n\x10vehicle_detected\x18\x02 \x01(\x08\x12\x12\n\nconfidence\x18\x03 \x01(\x02\"\xc4\x01\n\rEgressPayload\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12.\n\ntime_stamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10vehicle_detected\x18\x03 \x01(\x08\x12\x1c\n\x14\x64\x65tection_confidence\x18\x04 \x01(\x02\x12\x15\n\rvehicle_class\x18\x05 \x01(\t\x12!\n\x19\x63lassification_confidence\x18\x06 \x01(\x02\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSOR']._serialized_start=63
  _globals['_TENSOR']._serialized_end=100
  _globals['_SENSORDATA']._serialized_start=103
  _globals['_SENSORDATA']._serialized_end=387
  _globals['_DETECTIONRESULT']._serialized_start=389
  _globals['_DETECTIONRESULT']._serialized_end=496
  _globals['_EGRESSPAYLOAD']._serialized_start=499
  _globals['_EGRESSPAYLOAD']._serialized_end=695
  _globals['_ACK']._serialized_start=697
  _globals['_ACK']._serialized_end=736
# @@protoc_insertion_point(module_scope)
