#!/usr/bin/env bash
set -euo pipefail

# Split restructure for ID eval. Review before running.
# Generated from /Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed

echo "Removing accel + m3nvc multi-target + m3nvc background..."
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_bicycle2_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_bicycle2_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_bicycle2_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_bicycle2_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_bicycle_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_bicycle_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_bicycle_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_forester2_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_forester2_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_forester2_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_forester2_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_forester_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_forester_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_forester_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_forester_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_motor2_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_motor2_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_motor2_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_motor2_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_motor_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_motor_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_motor_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_motor_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_mustang0528_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_mustang2_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_mustang2_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_mustang_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_mustang_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_mustang_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_mustang_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_pickup2_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_pickup2_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_pickup2_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_pickup2_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_pickup_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_pickup_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_pickup_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_scooter2_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_scooter2_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_scooter2_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_scooter_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_scooter_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_scooter_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_scooter_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_tesla2_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_tesla2_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_tesla2_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_tesla2_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_tesla_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_tesla_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_walk2_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_walk2_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_walk2_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_walk_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_walk_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_accel_walk_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_background_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_background_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_background_rs5.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_background_rs6.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_background_rs8.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_miata_rs10.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_miata_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_miata_rs5.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_miata_rs6.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_miata_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_miata_rs8.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_mustang_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_mustang_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_mustang_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_mustang_rs5.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_mustang_rs6.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_mustang_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_miata_mustang_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_miata_mustang_rs10.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_miata_mustang_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_miata_mustang_rs5.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_miata_mustang_rs6.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_miata_mustang_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_miata_mustang_rs8.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_background_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_background_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_background_rs5.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_background_rs6.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_background_rs8.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_miata_rs10.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_miata_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_miata_rs5.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_miata_rs6.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_miata_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_miata_rs8.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_mustang_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_mustang_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_mustang_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_mustang_rs5.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_mustang_rs6.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_mustang_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_miata_mustang_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_miata_mustang_rs10.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_miata_mustang_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_miata_mustang_rs5.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_miata_mustang_rs6.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_miata_mustang_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_miata_mustang_rs8.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_accel_bicycle_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_accel_mustang0528_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_accel_mustang0528_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_accel_mustang0528_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_accel_mustang2_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_accel_mustang2_rs3.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_accel_pickup_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_accel_scooter2_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_accel_tesla_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_accel_tesla_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_accel_walk2_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_accel_walk_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_audio_background_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_audio_cx30_miata_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_audio_cx30_miata_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_audio_cx30_mustang_rs10.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_audio_cx30_mustang_rs8.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_audio_miata_mustang_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_seismic_background_rs7.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_seismic_cx30_miata_rs1.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_seismic_cx30_miata_rs2.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_seismic_cx30_mustang_rs10.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_seismic_cx30_mustang_rs8.parquet"
rm "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_seismic_miata_mustang_rs2.parquet"

echo "Moving files to new splits..."
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/iobt_audio_polaris0150pm_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/iobt_audio_polaris0150pm_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/iobt_audio_polaris0215pm_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/iobt_audio_polaris0215pm_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/iobt_audio_silverado0255pm_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/iobt_audio_silverado0255pm_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/iobt_audio_warhog1135am_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/iobt_audio_warhog1135am_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/iobt_audio_warhog1149am_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/iobt_audio_warhog1149am_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/iobt_audio_warhog_nolineofsight_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/iobt_audio_warhog_nolineofsight_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/iobt_seismic_polaris0150pm_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/iobt_seismic_polaris0150pm_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/iobt_seismic_polaris0215pm_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/iobt_seismic_polaris0215pm_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/iobt_seismic_silverado0255pm_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/iobt_seismic_silverado0255pm_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/iobt_seismic_warhog1135am_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/iobt_seismic_warhog1135am_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/iobt_seismic_warhog1149am_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/iobt_seismic_warhog1149am_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/iobt_seismic_warhog_nolineofsight_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/iobt_seismic_warhog_nolineofsight_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_bicycle_rs2.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_bicycle_rs2.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_bicycle_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_bicycle_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_bicycle_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_bicycle_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_forester2_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_forester2_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_forester2_rs2.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_forester2_rs2.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_forester2_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_forester2_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_forester2_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_forester2_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_motor2_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_motor2_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_motor2_rs2.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_motor2_rs2.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_motor2_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_motor2_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_motor2_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_motor2_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_pickup2_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_audio_pickup2_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_pickup2_rs2.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_audio_pickup2_rs2.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_pickup2_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_audio_pickup2_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_pickup2_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_audio_pickup2_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_scooter2_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_audio_scooter2_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_scooter2_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_audio_scooter2_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_scooter2_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_audio_scooter2_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_tesla2_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_tesla2_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_tesla2_rs2.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_tesla2_rs2.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_tesla2_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_tesla2_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_tesla2_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_tesla2_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_bicycle_rs2.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_bicycle_rs2.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_bicycle_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_bicycle_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_bicycle_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_bicycle_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_forester2_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_forester2_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_forester2_rs2.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_forester2_rs2.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_forester2_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_forester2_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_forester2_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_forester2_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_motor2_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_motor2_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_motor2_rs2.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_motor2_rs2.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_motor2_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_motor2_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_motor2_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_motor2_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_pickup2_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_seismic_pickup2_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_pickup2_rs2.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_seismic_pickup2_rs2.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_pickup2_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_seismic_pickup2_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_pickup2_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_seismic_pickup2_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_scooter2_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_seismic_scooter2_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_scooter2_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_seismic_scooter2_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_scooter2_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_seismic_scooter2_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_tesla2_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_tesla2_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_tesla2_rs2.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_tesla2_rs2.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_tesla2_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_tesla2_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_tesla2_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_tesla2_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_rs10.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_audio_cx30_rs10.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_cx30_rs8.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_audio_cx30_rs8.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_gle350_rs10.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_audio_gle350_rs10.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_gle350_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_audio_gle350_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_gle350_rs8.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_audio_gle350_rs8.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_miata_rs10.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_audio_miata_rs10.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_miata_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_audio_miata_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_miata_rs8.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_audio_miata_rs8.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_mustang_rs10.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_audio_mustang_rs10.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_mustang_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_audio_mustang_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_mustang_rs8.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_audio_mustang_rs8.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_rs10.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_seismic_cx30_rs10.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_cx30_rs8.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_seismic_cx30_rs8.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_gle350_rs10.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_seismic_gle350_rs10.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_gle350_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_seismic_gle350_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_gle350_rs8.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_seismic_gle350_rs8.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_miata_rs10.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_seismic_miata_rs10.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_miata_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_seismic_miata_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_miata_rs8.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_seismic_miata_rs8.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_mustang_rs10.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_seismic_mustang_rs10.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_mustang_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_seismic_mustang_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_mustang_rs8.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/m3nvc_seismic_mustang_rs8.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_mustang2_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_mustang2_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_mustang2_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_mustang2_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_pickup_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_pickup_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_scooter2_rs2.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_audio_scooter2_rs2.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_tesla_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_tesla_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_tesla_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_tesla_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_walk2_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_walk2_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_audio_walk_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_audio_walk_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_mustang2_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_mustang2_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_mustang2_rs3.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_mustang2_rs3.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_pickup_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_pickup_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_scooter2_rs2.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/test/focal_seismic_scooter2_rs2.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_tesla_rs1.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_tesla_rs1.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_tesla_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_tesla_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_walk2_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_walk2_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/focal_seismic_walk_rs7.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/focal_seismic_walk_rs7.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_audio_gle350_rs5.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_audio_gle350_rs5.parquet"
mv "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/val/m3nvc_seismic_gle350_rs5.parquet" "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/data_files/parsed/train/m3nvc_seismic_gle350_rs5.parquet"

echo "Clearing data cache..."
rm -rf "/Users/brandontaylor/Documents/CMU/CAPSTONE/Dark_Circle/crl-train/saved_crl/cache"/* 2>/dev/null || true
echo "Done."
