"""
plot_metrics.py
===============
Reads the training metrics CSVs generated by train_crl.py and outputs
easy-to-understand matplotlib graphs tracking the progression of losses,
regularizations, and evaluation metrics over the course of training.

Usage:
    poetry run python plot_metrics.py --save-dir ./saved_crl
"""

import argparse
import pandas as pd
import matplotlib

matplotlib.use("Agg")  # Use headless backend for server environments
import matplotlib.pyplot as plt
from pathlib import Path


def plot_crl_metrics(save_dir: Path):
    csv_path = save_dir / "crl_metrics.csv"
    if not csv_path.exists():
        print(f"Skipping Phase 1 plots: '{csv_path}' not found.")
        return

    df = pd.read_csv(csv_path)

    fig, axs = plt.subplots(1, 3, figsize=(18, 5))

    # 1. Overall Train vs Val Loss
    axs[0].plot(
        df["epoch"], df["train_loss"], label="Train Loss", color="blue", linewidth=2
    )
    axs[0].plot(
        df["epoch"], df["val_loss"], label="Val Loss", color="orange", linewidth=2
    )
    axs[0].set_title("CRL Phase 1: Total Loss")
    axs[0].set_xlabel("Epoch")
    axs[0].set_ylabel("Loss")
    axs[0].legend()
    axs[0].grid(True, linestyle="--", alpha=0.6)

    # 2. VICReg Components (Vehicle Identity)
    axs[1].plot(df["epoch"], df["vic_inv"], label="Invariance (MSE)", linewidth=2)
    axs[1].plot(df["epoch"], df["vic_var"], label="Variance (ReLU)", linewidth=2)
    axs[1].plot(df["epoch"], df["vic_cov"], label="Covariance (Off-diag)", linewidth=2)
    axs[1].set_title("z_veh: VICReg Regularization")
    axs[1].set_xlabel("Epoch")
    axs[1].set_ylabel("Loss Value")
    axs[1].legend()
    axs[1].grid(True, linestyle="--", alpha=0.6)

    # 3. Environment Components
    axs[2].plot(df["epoch"], df["kl_env"], label="KL (Env Prior)", linewidth=2)
    axs[2].plot(df["epoch"], df["slow"], label="Temporal Slowness", linewidth=2)
    axs[2].set_title("z_env: Disentanglement")
    axs[2].set_xlabel("Epoch")
    axs[2].set_ylabel("Loss Value")
    axs[2].legend()
    axs[2].grid(True, linestyle="--", alpha=0.6)

    plt.tight_layout()
    out_path = save_dir / "crl_training_graphs.png"
    plt.savefig(out_path, dpi=150)
    plt.close()
    print(f"Saved Phase 1 training graphs to {out_path}")


def plot_downstream_metrics(save_dir: Path):
    csv_path = save_dir / "downstream_metrics.csv"
    if not csv_path.exists():
        print(f"Skipping Phase 2 plots: '{csv_path}' not found.")
        return

    df = pd.read_csv(csv_path)

    fig, axs = plt.subplots(1, 2, figsize=(14, 5))

    # 1. Downstream Training Loss
    axs[0].plot(
        df["epoch"],
        df["train_det_loss"],
        label="Detection Loss (Train)",
        color="blue",
        linewidth=2,
    )
    axs[0].plot(
        df["epoch"],
        df["train_cls_loss"],
        label="Classification Loss (Train)",
        color="green",
        linewidth=2,
    )
    axs[0].set_title("Phase 2: Training Loss")
    axs[0].set_xlabel("Epoch")
    axs[0].set_ylabel("Loss")
    axs[0].legend()
    axs[0].grid(True, linestyle="--", alpha=0.6)

    # 2. Downstream Validation F1
    axs[1].plot(
        df["epoch"], df["val_det_f1"], label="Detection F1", color="blue", linewidth=2
    )
    axs[1].plot(
        df["epoch"],
        df["val_cls_f1"],
        label="Classification F1",
        color="green",
        linewidth=2,
    )
    axs[1].set_title("Phase 2: Validation F1 Scores")
    axs[1].set_xlabel("Epoch")
    axs[1].set_ylabel("F1 Score")
    axs[1].set_ylim(0.0, 1.05)
    axs[1].legend()
    axs[1].grid(True, linestyle="--", alpha=0.6)

    plt.tight_layout()
    out_path = save_dir / "downstream_training_graphs.png"
    plt.savefig(out_path, dpi=150)
    plt.close()
    print(f"Saved Phase 2 downstream graphs to {out_path}")


def main():
    parser = argparse.ArgumentParser(description="Plot CRL training metrics.")
    parser.add_argument(
        "--save-dir",
        default="./saved_crl",
        type=str,
        help="Directory containing the metrics CSVs (default: ./saved_crl).",
    )
    args = parser.parse_args()

    save_dir = Path(args.save_dir)
    if not save_dir.exists():
        print(f"Error: Directory {save_dir} does not exist.")
        return

    plot_crl_metrics(save_dir)
    plot_downstream_metrics(save_dir)


if __name__ == "__main__":
    main()
